### ISSUE TITLE
Cannot generate text for example=Siege of Chaves.txt

### ISSUE THREAD

**Issue by AtillaKaanAlkan** [nle18/coref-llms#1]
Hi @nle18 ,

First of all, thanks for this inspiring work!

I tried to run your code on the provided **example.jsonl** file with the following command as you indicated in the documentation:

`python src/main.py --exp_dir ./test --eval_data ./data/example.jsonl --model_id gpt-4 --prompt_template doc_template`

However, it looks like there is a problem in the text generation step (llm.py script). I tried with several other OpenAI models and I always get the same issue. Consequently all the scores are equal to 0. I have not been able to understand the issue. Can you help?

Here is the shell output:

> Token indices sequence length is longer than the specified maximum sequence length for this model (2532 > 1024). Running this sequence through the model will result in indexing errors
> Dataset has 1 examples
> max_len: 8000
> Estimated cost for gpt-4: $0.40
> Cannot generate text for example=Siege of Chaves.txt
> Something wrong with doc_key=Siege of Chaves.txt
> Process 0 out of 1 docs (0.00%)
> Evaluating 0 docs
> CoNLL F1 = 0.0
> Detailed F1s = {'muc': ('Recall: 0.0, Precision: 0.0, ', 'F-score:  0.0\n'), 'b_cubed': ('Recall: 0.0, Precision: 0.0, ', 'F-score:  0.0\n'), 'ceafe': ('Recall: 0.0, Precision: 0.0, ', 'F-score:  0.0\n')}

**Comment by nle18** [comment]
Hi @AtillaKaanAlkan,

I just ran the code as instructed in the README and was able to run the output successfully: 
`Token indices sequence length is longer than the specified maximum sequence length for this model (2532 > 1024). Running this sequence through the model will result in indexing errors
Dataset has 1 examples
Estimated cost for gpt-4: $0.40
Process 1 out of 1 docs (100.00%)
Evaluating 1 docs
CoNLL F1 = 0.8436986051753467
Detailed F1s = {'muc': ('Recall: 90.8, Precision: 88.5, ', 'F-score:  89.7\n'), 'b_cubed': ('Recall: 84.8, Precision: 79.1, ', 'F-score:  81.8\n'), 'ceafe': ('Recall: 77.6, Precision: 86.0, ', 'F-score:  81.6\n')}
`
Seems like your problem is with the program outputs `Cannot generate text for example=Siege of Chaves.txt`. You can try remove the `try-except` in OpenAI class of `src/llms.py` file to debug. Maybe it's an issue with OpenAI API?

**Comment by AtillaKaanAlkan** [comment]
Hi @nle18 ,

Thanks for your answer! I removed the try-except from the OpenAI class. Indeed it removed the `Cannot generate text for example=Siege of Chaves.txt`
from the output.

However, the document seems to still not be processed:
 
> Token indices sequence length is longer than the specified maximum sequence length for this model (2532 > 1024). Running this sequence through the model will result in indexing errors
> Dataset has 1 examples
> max_len: 4000
> Estimated cost for gpt-3.5-turbo: $0.01
> Process 0 out of 1 docs (0.00%)
> Evaluating 0 docs
> CoNLL F1 = 0.0
> Detailed F1s = {'muc': ('Recall: 0.0, Precision: 0.0, ', 'F-score:  0.0\n'), 'b_cubed': ('Recall: 0.0, Precision: 0.0, ', 'F-score:  0.0\n'), 'ceafe': ('Recall: 0.0, Precision: 0.0, ', 'F-score:  0.0\n')}

I am wondering if the error may come from a modification I did from your original code. Indeed, at line 26 of your **data_processing.py** script, the `dataset_reader = DATASET_READERS[args.example_type](
        gold_data, predicted_data, tokenizer
    )` was causing an error since there is no such a defined args (`example_type`). To solve this error, I replaced it with `dataset_reader = DATASET_READERS["doc_example"](
        gold_data, predicted_data, tokenizer
    )` . I don't know if that can cause the actual issue I have?

**Comment by nle18** [comment]
The modification makes sense; I haven't updated the codebase in a bit. Just fixed the bug you mentioned. However, that should not cause the problem with the generation. If the LLM successfully generated the text, there would have been a printed message. The lack of this printed message makes me think it has something to do with the API calls instead.

**Comment by AtillaKaanAlkan** [comment]
Hi @nle18 , 

I re-tested this morning and I get right now the results:

```
Process 1 out of 1 docs (100.00%)
Evaluating 1 docs
CoNLL F1 = 0.8377302200327253
Detailed F1s = {'muc': ('Recall: 93.5, Precision: 88.8, ', 'F-score:  91.1\n'), 'b_cubed': ('Recall: 90.6, Precision: 75.7, ', 'F-score:  82.5\n'), 'ceafe': ('Recall: 70.1, Precision: 87.1, ', 'F-score:  77.7\n')}
```

There was certainly something wrong with the API call...

Thanks again for your answer and your help! I am closing the issue! :)
